### ISSUE TITLE
Kills processes that print to stderr

### ISSUE THREAD

**Issue by TheSavior** [patrick-steele-idem/child-process-promise#18]
If you spawn npm install, you'll get warning messages like:

```
npm WARN package.json pkgName@2.2.1 No license field.
```

And this is printed to stderr, which triggers

```
cp.on('error', deferred.reject);
```
at https://github.com/patrick-steele-idem/child-process-promise/blob/master/lib/index.js#L120

**Comment by patrick-steele-idem** [comment]
I just double checked and writing to stderr does not cause the promise to be rejected. The `error` event does _not_ get emitted when writing to `stderr`: https://nodejs.org/api/child_process.html#child_process_event_error

I added a test case to verify and everything is working as expected (the promise is not rejected when writing to stderr): https://github.com/patrick-steele-idem/child-process-promise/commit/2a650240d459dc5fcaba58b20c3ce69f164938e8

Please let me know if I am missing anything.

**Comment by TheSavior** [comment]
Well, glad you added a test case. Sad it wasn't the problem. haha

It appears that I was running npm install and it was passing through the NODE_ENV to the child process which since it returned early and didn't install the packages I was expecting was causing things to throw. Sorry for the goose-chase.
