### ISSUE TITLE
missing stream output

### ISSUE THREAD

**Issue by syzer** [patrick-steele-idem/child-process-promise#27]
normal node `spawn` can get us also stream of data. Is it possible to get a stream from `chld-process-promise` `spawn` command ?

**Comment by olsonpm** [comment]
If I'm understanding your question correctly, the README.md example spells this out

```
var spawn = require('child-process-promise').spawn;

var promise = spawn('echo', ['hello']);

var childProcess = promise.childProcess;

console.log('[spawn] childProcess.pid: ', childProcess.pid);
childProcess.stdout.on('data', function (data) { // <---------------- attaching to spawned stdout
    console.log('[spawn] stdout: ', data.toString());
});
childProcess.stderr.on('data', function (data) {
    console.log('[spawn] stderr: ', data.toString());// // <---------------- attaching to spawned stderr
});

promise.then(function () {
        console.log('[spawn] done!');
    })
    .catch(function (err) {
        console.error('[spawn] ERROR: ', err);
    });
```

**Comment by patrick-steele-idem** [comment]
@syzer I'm going to go ahead and close this issue because, as @olsonpm pointed out, you have access to the `stdout` and `stderr` streams via `promise.childProcess` object. If that doesn't solve your problem please reopen with more details or feel free to put comments here.

**Comment by syzer** [comment]
thanks!  i guess i should have RTFM :)

**Comment by olsonpm** [comment]
happens to the best of us

**Comment by tarundhillon** [comment]
This method works for getting the standard stdout where each line is appended as a new line, but in cases where the same line is overwritten I am struggling to get the output to stream. 

I.e during the Angular's ng build -- the % completion of files processed is shown in an single overwritten line. Any suggestions on how to capture these outputs ? Thanks

**Comment by syzer** [comment]
@tarundhillon `promise.childProcess.stdout.on('data', console.log)` ?

**Comment by tarundhillon** [comment]
@syzer nope this also doesnt work, it tries to print the buffer 

`<Buffer 4c 4f 47 3a 20 27 41 74 74 65 6e 74 69 6f 6e 20 2d 20 4e 6f 20 75 73 65 72 20 66 6f 75 6e 64 27 0a>
<Buffer 4c 4f 47 3a 20 27 41 74 74 65 6e 74 69 6f 6e 20 2d 20 4e 6f 20 75 73 65 72 20 66 6f 75 6e 64 27 0a>
<`

**Comment by syzer** [comment]
@tarundhillon call `.toString()`
