### ISSUE TITLE
Warning: a promise was rejected with a non-error object

### ISSUE THREAD

**Issue by olivierto** [patrick-steele-idem/child-process-promise#30]
Hello! 
I'm using Bluebird.js  and your package. 
I'm facing a little warning which leads to an error for my specific code for error handling. 
It seems that when your getting an error in index.js   cp.on('close') function, your not creating an Error object but a basic object.

I think you should consider reject promises with real error objects to make this compatible with well known promise library like bluebird or q 

Thanks.

**Comment by olsonpm** [comment]
I have a feeling if you created a PR this would get merged.

**Comment by olivierto** [comment]
here it is! #31

**Comment by olivierto** [comment]
#31

**Comment by patrick-steele-idem** [comment]
Fixed by https://github.com/patrick-steele-idem/child-process-promise/pull/31

New version published: `child-process-promise@2.2.1`

Thanks guys.
