### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by TheDSCPL** [patrick-steele-idem/child-process-promise#43]
Hello!

Are there going to be type definition files for this package in Definitely Typed any time soon? I never expected a library that is downloaded 328667 times per week (at the time of writing) to not have a definition file!

Please consider creating one or writing a more thoroughly detailed documentation page so I can write it myself.

**Comment by jassmith** [comment]
This project is pretty clearly dead. Is there an actively maintained fork?

**Comment by TheDSCPL** [comment]
Not that I know of! It's a shame because it is a very handy module.

**Comment by GaikwadPratik** [comment]
You might want to switch to https://github.com/jcoreio/promisify-child-process

**Comment by TheDSCPL** [comment]
I've created the typescript definition of this package and merged it into the DefinitelyTyped repository so it is now available in npm and you can install it by running `npm i -D @types/child-process-promise`

**Comment by patrick-steele-idem** [comment]
I don't mind adding someone trustworthy as a maintainer. At the moment, I still do not have time to focus on open source. Please let me know if there is interest.
